env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - prettier
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
root: true
rules: {}
